### ISSUE TITLE
Cleaning up binary files

### ISSUE THREAD

**Issue by usert5432** [LS4GAN/toytools#17]
We have binary/temp files that have accidentally made their way into the master branch. Now, they are forever stuck in our git history and are going to needlessly increase the size of the git repo. I was wondering what do you think if we force overwrite the git history to completely remove these files and then reset the head of the master branch?

To illustrate what I am suggesting, I have made a branch, [clean_master](https://github.com/usert5432/toytools/tree/clean_master) in my personal repo. In that branch, I have squashed all commits that introduce/remove binary and temp files into one (before: b2926e789de6848adcd5ee40334a5c6672f73f0f, after: 62789d636966dcb2c73b2d135b95d3882579698a) and completely removed these files from the history.

@brettviren could I ask you please whether you think such a history overwriting is a good idea?

**Comment by brettviren** [comment]
I think we need not be afraid to rewrite history to solve these kind of problems.  And doing it sooner is better than doing it later.

Of course the rewrite will invalidate any existing "clones".  Right now, this would not scare me as we must have only a small number of clones and they can be easily abandoned/purged.

However, I just did a fresh clone of `toytools` from `ls4gan` and your fork and do not see a noticeable problem.  Here is toytools master (`toytools-test`) and `clean_branch` from your fork:

```
❯ git clone git@github.com:LS4GAN/toytools.git toytools-test
❯ du -sh toytools-test
428K	toytools-test
❯ du -sh toytools-test/.git
252K	toytools-test/.git

❯ git clone https://github.com/usert5432/toytools.git toytools-clean-master
❯ du -sh toytools-clean-master
372K	toytools-clean-master
❯ du -sh toytools-clean-master/.git
264K	toytools-clean-master/.git
```

Strangely, the `.git/` from your fork is slightly larger.

I wonder if I am somehow not catching the problematic commits?

**Comment by usert5432** [comment]
Thank you for looking into this issue @brettviren!

> Strangely, the .git/ from your fork is slightly larger.
> I wonder if I am somehow not catching the problematic commits?

I am not an expert on git, but I believe by default it `clone`s an entire repository. Since, my repo has many more branches than this one, it will occupy more space. I have tried `clone`-ing only master branches and checked their sizes:
```bash
$ git clone https://github.com/usert5432/toytools.git toytools-clean-master -b clean_master --single-branch
$ git clone https://github.com/LS4GAN/toytools.git toytools-test -b master --single-branch

$ du -sh */.git
152K    toytools-clean-master/.git
180K    toytools-test/.git
```

When only master branches are considered my repo looks smaller.

**Comment by usert5432** [comment]
Sorry for bugging you again @brettviren, will you give me a green light to implement this history overwriting?

**Comment by brettviren** [comment]
Yes, of course.  Please proceed as you see fit.

**Comment by usert5432** [comment]
Ok, Thank you. I have overwritten the history and removed the binary/temp files from it.
